-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 18:21:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fabdev_fixmycar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fabdev_fixmycar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fabdev_fixmycar` DEFAULT CHARACTER SET utf8 ;
USE `fabdev_fixmycar` ;

-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Oficina` (
  `Cod_Of` INT NOT NULL AUTO_INCREMENT,
  `Nome_Completo` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Nome_Oficina` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Whatsapp` VARCHAR(11) NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  `Bairro` VARCHAR(30) NOT NULL,
  `Rua/Avenida` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(20) NOT NULL,
  `Complemento` VARCHAR(20) NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Cod_Of`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Cadastro Oficina PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Cadastro Oficina PF` (
  `Data_Nascimento` DATE NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`Oficina_Cod_Of`),
  CONSTRAINT `fk_Cadastro Oficina Pessoa Fisica_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Cadastro_Oficina_ PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Cadastro_Oficina_ PJ` (
  `CNPJ` VARCHAR(14) NOT NULL,
  `Razao_Social` VARCHAR(255) NOT NULL,
  `Nome_Fantasia` VARCHAR(255) NOT NULL,
  `Inscricao_Estadual` VARCHAR(45) NOT NULL,
  `PIS` VARCHAR(11) NOT NULL,
  `Oficina_Cod_Of` INT NOT NULL,
  PRIMARY KEY (`Oficina_Cod_Of`),
  CONSTRAINT `fk_Cadastro_Oficina_ PJ_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Filial` (
  `Cod_filial` INT(8) NOT NULL,
  `NOME_FILIAL` VARCHAR(50) NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`Cod_filial`),
  INDEX `fk_Filial_Oficina1_idx` (`Oficina_Cod_Of` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`MENSALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`MENSALIDADE` (
  `idMENS` INT(8) NOT NULL,
  `DATA` DATETIME NOT NULL,
  `CATEGORIA` VARCHAR(20) NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`idMENS`),
  INDEX `fk_MENSALIDADE_Oficina1_idx` (`Oficina_Cod_Of` ASC) VISIBLE,
  CONSTRAINT `fk_MENSALIDADE_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`SUPORTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`SUPORTE` (
  `CHAMADO` INT(8) NOT NULL,
  `DESCRICAO` LONGTEXT NOT NULL,
  `PROTOCOLO` VARCHAR(11) NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`CHAMADO`),
  INDEX `fk_SUPORTE_Oficina1_idx` (`Oficina_Cod_Of` ASC) VISIBLE,
  CONSTRAINT `fk_SUPORTE_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`COLABORADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`COLABORADORES` (
  `idCOLABORADORES` INT(8) NOT NULL AUTO_INCREMENT,
  `Nome Completo` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Whatsapp` VARCHAR(11) NOT NULL,
  `CARGO` VARCHAR(45) NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`idCOLABORADORES`),
  INDEX `fk_COLABORADORES_Oficina1_idx` (`Oficina_Cod_Of` ASC) VISIBLE,
  CONSTRAINT `fk_COLABORADORES_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ATENDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ATENDENTE` (
  `idATENDENTE` INT(8) NOT NULL AUTO_INCREMENT,
  `COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  PRIMARY KEY (`COLABORADORES_idCOLABORADORES`),
  CONSTRAINT `fk_ATENDENTE_COLABORADORES1`
    FOREIGN KEY (`COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`COLABORADORES` (`idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`MECANICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`MECANICO` (
  `idMECANICO` INT(8) NOT NULL,
  `COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  PRIMARY KEY (`COLABORADORES_idCOLABORADORES`),
  CONSTRAINT `fk_MECANICO_COLABORADORES1`
    FOREIGN KEY (`COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`COLABORADORES` (`idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`CLIENTE` (
  `idCLIENTE` INT(8) NOT NULL,
  `Nome_Completo` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Whatsapp` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `UF` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  `Bairro` VARCHAR(30) NOT NULL,
  `Rua/Avenida` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(20) NOT NULL,
  `Complemento` VARCHAR(20) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`RELATORIO_FINAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`RELATORIO_FINAL` (
  `idRELATORIO_FINAL` INT(8) NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  PRIMARY KEY (`idRELATORIO_FINAL`),
  INDEX `fk_RELATORIO_FINAL_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_RELATORIO_FINAL_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ATENDIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ATENDIMENTO` (
  `idATE` INT(8) NOT NULL,
  `AGENDA` DATETIME(6) NOT NULL,
  `ATENDENTE_COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  `RELATORIO_FINAL_idRELATORIO_FINAL` INT(8) NOT NULL,
  PRIMARY KEY (`idATE`),
  INDEX `fk_ATENDIMENTO_ATENDENTE1_idx` (`ATENDENTE_COLABORADORES_idCOLABORADORES` ASC) VISIBLE,
  INDEX `fk_ATENDIMENTO_RELATORIO_FINAL1_idx` (`RELATORIO_FINAL_idRELATORIO_FINAL` ASC) VISIBLE,
  CONSTRAINT `fk_ATENDIMENTO_ATENDENTE1`
    FOREIGN KEY (`ATENDENTE_COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`ATENDENTE` (`COLABORADORES_idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATENDIMENTO_RELATORIO_FINAL1`
    FOREIGN KEY (`RELATORIO_FINAL_idRELATORIO_FINAL`)
    REFERENCES `fabdev_fixmycar`.`RELATORIO_FINAL` (`idRELATORIO_FINAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`VEICULO` (
  `idVEICULO` INT(8) NOT NULL AUTO_INCREMENT,
  `Renavan` VARCHAR(15) NOT NULL,
  `Placa` VARCHAR(10) NOT NULL,
  `Tipo_Veiculo` VARCHAR(25) NOT NULL,
  `Modelo/Versao` VARCHAR(25) NOT NULL,
  `Marca` VARCHAR(15) NOT NULL,
  `ano_de_fabricacao` YEAR(4) NOT NULL,
  `Cor` VARCHAR(15) NOT NULL,
  `Combustivel` VARCHAR(15) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  PRIMARY KEY (`idVEICULO`),
  INDEX `fk_VEICULO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`RECIBO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`RECIBO` (
  `idRECIBO` INT(8) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  `descricao_Recibo` VARCHAR(255) NULL,
  PRIMARY KEY (`idRECIBO`),
  INDEX `fk_RECIBO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_RECIBO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`FINANCEIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`FINANCEIRO` (
  `idFINANCEIRO` INT(8) NOT NULL,
  PRIMARY KEY (`idFINANCEIRO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Nota_de_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Nota_de_Servico` (
  `idNFServico` INT(8) NOT NULL,
  `Observacoes` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  `FINANCEIRO_idFINANCEIRO` INT(8) NOT NULL,
  PRIMARY KEY (`idNFServico`),
  INDEX `fk_Nota_de_Servico_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_Nota_de_Servico_FINANCEIRO1_idx` (`FINANCEIRO_idFINANCEIRO` ASC) VISIBLE,
  CONSTRAINT `fk_Nota_de_Servico_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_de_Servico_FINANCEIRO1`
    FOREIGN KEY (`FINANCEIRO_idFINANCEIRO`)
    REFERENCES `fabdev_fixmycar`.`FINANCEIRO` (`idFINANCEIRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (
  `idNFISCAL` INT(8) NOT NULL COMMENT 'Tipo_de_Emissao VARCHAR(45)\nFinalidade VARCHAR(45)\nNatureza_da_Operacao VARCHAR(45)\nIndicador_de Presenca VARCHAR(45)\nCliente Final VARCHAR(45)\nData_de_Emissao VARCHAR(45)\nDestinatario VARCHAR(45)\nValores_e_Impostos VARCHAR(45)\nOutros _Impostos VARCHAR(45)\nTransportador_Volume VARCHAR(45)\nItens VARCHAR(45)\nICMS VARCHAR(45)\nIPI VARCHAR(45)\nPIS VARCHAR(45)\nCOFINS VARCHAR(45)\nICMS ST VARCHAR(45)\nICMS UF DESTINO VARCHAR(45)\nICMS UF DESTINO VARCHAR(45)\nIBPT (INSTITUTO BRASILEIRO DE PLANEJAMENTO E…\nCLIENTE_id_CLIENTE INT',
  `Tipo_de_Emissao` VARCHAR(45) NULL,
  `Finalidade` VARCHAR(45) NULL,
  `Natureza_da_Operacao` VARCHAR(45) NULL,
  `Indicador_de_Presenca` VARCHAR(45) NULL,
  `Cliente Final` VARCHAR(45) NULL,
  `Data_de_Emissao` DATE NULL,
  `Destinatario` VARCHAR(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `FINANCEIRO_idFINANCEIRO` INT NOT NULL,
  PRIMARY KEY (`idNFISCAL`),
  INDEX `fk_NOTA_FISCAL_SAIDA1_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_NOTA_FISCAL_SAIDA1_FINANCEIRO1_idx` (`FINANCEIRO_idFINANCEIRO` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FISCAL_SAIDA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FISCAL_SAIDA_FINANCEIRO1`
    FOREIGN KEY (`FINANCEIRO_idFINANCEIRO`)
    REFERENCES `fabdev_fixmycar`.`FINANCEIRO` (`idFINANCEIRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ORDEM_SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ORDEM_SERVICO` (
  `OS` INT(8) NOT NULL AUTO_INCREMENT,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  `MECANICO_COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  `ATENDENTE_COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  `VEICULO_idVEICULO` INT(8) NOT NULL,
  `RELATORIO_FINAL_idRELATORIO_FINAL` INT(8) NOT NULL,
  `RECIBO_idRECIBO` INT(8) NOT NULL,
  `Nota_de_Servico_idNFServico` INT(8) NOT NULL,
  `Data_de_entrada` DATETIME NOT NULL,
  `Total_servicos` DECIMAL(6,2) NOT NULL,
  `Data_termino` DATETIME NOT NULL,
  `Total_pecas` DECIMAL(6,2) NOT NULL,
  `Total_ordem_servico` DECIMAL(6,2) NOT NULL,
  `Desconto` DECIMAL(6,2) NOT NULL,
  `Garantia` VARCHAR(10) NULL,
  `Informacoes_garantia` LONGTEXT NULL,
  `Observacoes_do_Servico` LONGTEXT NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  PRIMARY KEY (`OS`),
  INDEX `fk_ORDEM_SERVICO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_MECANICO1_idx` (`MECANICO_COLABORADORES_idCOLABORADORES` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_ATENDENTE1_idx` (`ATENDENTE_COLABORADORES_idCOLABORADORES` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_VEICULO1_idx` (`VEICULO_idVEICULO` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_RELATORIO_FINAL1_idx` (`RELATORIO_FINAL_idRELATORIO_FINAL` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_RECIBO1_idx` (`RECIBO_idRECIBO` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_Nota_de_Servico1_idx` (`Nota_de_Servico_idNFServico` ASC) VISIBLE,
  INDEX `fk_ORDEM_SERVICO_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEM_SERVICO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_MECANICO1`
    FOREIGN KEY (`MECANICO_COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`MECANICO` (`COLABORADORES_idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_ATENDENTE1`
    FOREIGN KEY (`ATENDENTE_COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`ATENDENTE` (`COLABORADORES_idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_VEICULO1`
    FOREIGN KEY (`VEICULO_idVEICULO`)
    REFERENCES `fabdev_fixmycar`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_RELATORIO_FINAL1`
    FOREIGN KEY (`RELATORIO_FINAL_idRELATORIO_FINAL`)
    REFERENCES `fabdev_fixmycar`.`RELATORIO_FINAL` (`idRELATORIO_FINAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_RECIBO1`
    FOREIGN KEY (`RECIBO_idRECIBO`)
    REFERENCES `fabdev_fixmycar`.`RECIBO` (`idRECIBO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_Nota_de_Servico1`
    FOREIGN KEY (`Nota_de_Servico_idNFServico`)
    REFERENCES `fabdev_fixmycar`.`Nota_de_Servico` (`idNFServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEM_SERVICO_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`PosVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`PosVenda` (
  `PosVenda` INT(8) NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  `ATENDIMENTO_idATE` INT(8) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  `ORDEM_SERVICO_OS` INT(8) NOT NULL,
  PRIMARY KEY (`PosVenda`),
  INDEX `fk_PosVenda_ATENDIMENTO1_idx` (`ATENDIMENTO_idATE` ASC) VISIBLE,
  INDEX `fk_PosVenda_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_PosVenda_ORDEM_SERVICO1_idx` (`ORDEM_SERVICO_OS` ASC) VISIBLE,
  CONSTRAINT `fk_PosVenda_ATENDIMENTO1`
    FOREIGN KEY (`ATENDIMENTO_idATE`)
    REFERENCES `fabdev_fixmycar`.`ATENDIMENTO` (`idATE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PosVenda_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PosVenda_ORDEM_SERVICO1`
    FOREIGN KEY (`ORDEM_SERVICO_OS`)
    REFERENCES `fabdev_fixmycar`.`ORDEM_SERVICO` (`OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`CATEGORIA_SERVICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`CATEGORIA_SERVICOS` (
  `idCAT_SERVICOS` INT(8) NOT NULL,
  `CATEGORIA_SERVICOS` VARCHAR(255) NOT NULL,
  `Oficina_Cod_Of` INT(8) NOT NULL,
  PRIMARY KEY (`idCAT_SERVICOS`),
  INDEX `fk_CATEGORIA_SERVICOS_Oficina1_idx` (`Oficina_Cod_Of` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIA_SERVICOS_Oficina1`
    FOREIGN KEY (`Oficina_Cod_Of`)
    REFERENCES `fabdev_fixmycar`.`Oficina` (`Cod_Of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`TIPO_SERVICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`TIPO_SERVICOS` (
  `idT_SERVICOS` INT(8) NOT NULL AUTO_INCREMENT,
  `CATEGORIA_SERVICOS_idCAT_SERVICOS` INT(8) NOT NULL,
  `TIPO_SERVICOS` VARCHAR(45) NOT NULL,
  `DESCRICAO_SERVICOS` VARCHAR(255) NOT NULL,
  `CUSTO_SERVIÇO_HORA` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idT_SERVICOS`),
  INDEX `fk_TIPO_SERVICOS_CATEGORIA_SERVICOS1_idx` (`CATEGORIA_SERVICOS_idCAT_SERVICOS` ASC) VISIBLE,
  CONSTRAINT `fk_TIPO_SERVICOS_CATEGORIA_SERVICOS1`
    FOREIGN KEY (`CATEGORIA_SERVICOS_idCAT_SERVICOS`)
    REFERENCES `fabdev_fixmycar`.`CATEGORIA_SERVICOS` (`idCAT_SERVICOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ORCAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ORCAMENTO` (
  `idORCAMENTO` INT(8) NOT NULL AUTO_INCREMENT,
  `RELATORIO_FINAL_idRELATORIO_FINAL` INT(8) NOT NULL,
  `ORDEM_SERVICO_OS` INT(8) NOT NULL,
  `VEICULO_idVEICULO` INT(8) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  `SOLICITACAO_CLIENTE` LONGTEXT NOT NULL,
  PRIMARY KEY (`idORCAMENTO`),
  INDEX `fk_ORCAMENTO_RELATORIO_FINAL1_idx` (`RELATORIO_FINAL_idRELATORIO_FINAL` ASC) VISIBLE,
  INDEX `fk_ORCAMENTO_ORDEM_SERVICO1_idx` (`ORDEM_SERVICO_OS` ASC) VISIBLE,
  INDEX `fk_ORCAMENTO_VEICULO1_idx` (`VEICULO_idVEICULO` ASC) VISIBLE,
  INDEX `fk_ORCAMENTO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ORCAMENTO_RELATORIO_FINAL1`
    FOREIGN KEY (`RELATORIO_FINAL_idRELATORIO_FINAL`)
    REFERENCES `fabdev_fixmycar`.`RELATORIO_FINAL` (`idRELATORIO_FINAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORCAMENTO_ORDEM_SERVICO1`
    FOREIGN KEY (`ORDEM_SERVICO_OS`)
    REFERENCES `fabdev_fixmycar`.`ORDEM_SERVICO` (`OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORCAMENTO_VEICULO1`
    FOREIGN KEY (`VEICULO_idVEICULO`)
    REFERENCES `fabdev_fixmycar`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORCAMENTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`SERVICOS_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`SERVICOS_VENDA` (
  `idSERVICOS` INT(8) NOT NULL AUTO_INCREMENT,
  `TIPO_SERVICOS_idT_SERVICOS` INT(8) NOT NULL,
  `TEMPO_ESTIMADO` TIME NOT NULL,
  `TEMPO_EFETIVO` TIME NOT NULL,
  `CUSTO_ESTIMADO` DECIMAL(6,2) NOT NULL,
  `CUSTO_EFETIVO` DECIMAL(6,2) NOT NULL,
  `ORDEM_SERVICO_OS` INT(8) NOT NULL,
  `ORCAMENTO_idORCAMENTO` INT(8) NOT NULL,
  PRIMARY KEY (`idSERVICOS`),
  INDEX `fk_SERVICOS_VENDA_TIPO_SERVICOS1_idx` (`TIPO_SERVICOS_idT_SERVICOS` ASC) VISIBLE,
  INDEX `fk_SERVICOS_VENDA_ORDEM_SERVICO1_idx` (`ORDEM_SERVICO_OS` ASC) VISIBLE,
  INDEX `fk_SERVICOS_VENDA_ORCAMENTO1_idx` (`ORCAMENTO_idORCAMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICOS_VENDA_TIPO_SERVICOS1`
    FOREIGN KEY (`TIPO_SERVICOS_idT_SERVICOS`)
    REFERENCES `fabdev_fixmycar`.`TIPO_SERVICOS` (`idT_SERVICOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_VENDA_ORDEM_SERVICO1`
    FOREIGN KEY (`ORDEM_SERVICO_OS`)
    REFERENCES `fabdev_fixmycar`.`ORDEM_SERVICO` (`OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_VENDA_ORCAMENTO1`
    FOREIGN KEY (`ORCAMENTO_idORCAMENTO`)
    REFERENCES `fabdev_fixmycar`.`ORCAMENTO` (`idORCAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`FORNECEDOR` (
  `idFORNECEDOR` INT(8) NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(255) NOT NULL,
  `Nome_Fantasia` VARCHAR(255) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `Contato` VARCHAR(255) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Whatsapp` VARCHAR(11) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  `Bairro` VARCHAR(30) NOT NULL,
  `Rua` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(20) NOT NULL,
  `Complemento` VARCHAR(20) NULL,
  PRIMARY KEY (`idFORNECEDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`NOTA_FISCAL_Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`NOTA_FISCAL_Entrada` (
  `idNFISCAL_Entrada` INT(8) NOT NULL AUTO_INCREMENT,
  `numeroNota` INT(8) NOT NULL,
  `dataEmissao` DATETIME(6) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `dataPagamento` DATE NOT NULL,
  `valor_NOTA` DECIMAL(6,2) NOT NULL,
  `FORNECEDOR_idFORNECEDOR` INT(8) NOT NULL,
  `FINANCEIRO_idFINANCEIRO` INT(8) NOT NULL,
  PRIMARY KEY (`idNFISCAL_Entrada`),
  INDEX `fk_NOTA_FISCAL_Entrada_FORNECEDOR1_idx` (`FORNECEDOR_idFORNECEDOR` ASC) VISIBLE,
  INDEX `fk_NOTA_FISCAL_Entrada_FINANCEIRO1_idx` (`FINANCEIRO_idFINANCEIRO` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FISCAL_Entrada_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_idFORNECEDOR`)
    REFERENCES `fabdev_fixmycar`.`FORNECEDOR` (`idFORNECEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FISCAL_Entrada_FINANCEIRO1`
    FOREIGN KEY (`FINANCEIRO_idFINANCEIRO`)
    REFERENCES `fabdev_fixmycar`.`FINANCEIRO` (`idFINANCEIRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ESTOQUE` (
  `idESTOQUE` INT(8) NOT NULL,
  `PROD_codPROD_OFICINA` VARCHAR(16) NOT NULL,
  `PROD_nomePRODUTO` VARCHAR(50) NOT NULL,
  `PROD_valorProduto` DECIMAL(6,2) NOT NULL,
  `valorVENDA` DECIMAL(6,2) NOT NULL,
  `qtidadePRODUTO` INT NOT NULL,
  `PROD_UNIDADE` VARCHAR(20) NOT NULL,
  `ESTOQUEminimo` INT NOT NULL,
  PRIMARY KEY (`idESTOQUE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`PRODUTO_ENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`PRODUTO_ENT` (
  `idPRODUTO_ENT` INT(8) NOT NULL AUTO_INCREMENT COMMENT 'idPRODUTO INT(8)\ncodPRODUTO_Fornecedor INT\ncodPRODUTO_Oficina VARCHAR…\nnomePRODUTO VARCHAR(20)\ndescricaoPRODUTO VARCHAR(45)\nvalorPRODUTO DECIMAL(6,2)\nqtidadePRODUTO INT(8)\nUNIDADE VARCHAR(10)\nNOTA_FISCAL_idNFISCAL INT(8)\nFORNECEDOR_idFORNECEDOR INT(8)',
  `codPRODUTO_Fornecedor` VARCHAR(16) NOT NULL,
  `codPRODUTO_Oficina` VARCHAR(16) NOT NULL,
  `nomePRODUTO` VARCHAR(50) NOT NULL,
  `descricaoPRODUTO` VARCHAR(255) NOT NULL,
  `valorPRODUTO` DECIMAL(6,2) NOT NULL,
  `qtidadePRODUTO` DECIMAL(6,2) NOT NULL,
  `UNIDADE` VARCHAR(20) NOT NULL,
  `FORNECEDOR_idFORNECEDOR` INT(8) NOT NULL,
  `NOTA_FISCAL_Entrada_idNFISCAL_Entrada` INT(8) NOT NULL,
  PRIMARY KEY (`idPRODUTO_ENT`),
  INDEX `fk_PRODUTO_ENT_FORNECEDOR1_idx` (`FORNECEDOR_idFORNECEDOR` ASC) VISIBLE,
  INDEX `fk_PRODUTO_ENT_NOTA_FISCAL_Entrada1_idx` (`NOTA_FISCAL_Entrada_idNFISCAL_Entrada` ASC) VISIBLE,
  INDEX `fk_PRODUTO_ENT_ESTOQUE1_idx` (`codPRODUTO_Oficina` ASC) VISIBLE,
  INDEX `fk_PRODUTO_ENT_ESTOQUE2_idx` (`nomePRODUTO` ASC) VISIBLE,
  INDEX `fk_PRODUTO_ENT_ESTOQUE3_idx` (`valorPRODUTO` ASC) VISIBLE,
  INDEX `fk_PRODUTO_ENT_ESTOQUE4_idx` (`UNIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_ENT_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_idFORNECEDOR`)
    REFERENCES `fabdev_fixmycar`.`FORNECEDOR` (`idFORNECEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_ENT_NOTA_FISCAL_Entrada1`
    FOREIGN KEY (`NOTA_FISCAL_Entrada_idNFISCAL_Entrada`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_Entrada` (`idNFISCAL_Entrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_ENT_ESTOQUE1`
    FOREIGN KEY (`codPRODUTO_Oficina`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`PROD_codPROD_OFICINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_ENT_ESTOQUE2`
    FOREIGN KEY (`nomePRODUTO`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`PROD_nomePRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_ENT_ESTOQUE3`
    FOREIGN KEY (`valorPRODUTO`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`PROD_valorProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_ENT_ESTOQUE4`
    FOREIGN KEY (`UNIDADE`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`PROD_UNIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`CLIENTE_PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`CLIENTE_PJ` (
  `CNPJ` INT(8) NOT NULL,
  `Razao_Social` VARCHAR(255) NOT NULL,
  `Nome_Fantasia` VARCHAR(255) NOT NULL,
  `Inscricao_Estadual` VARCHAR(11) NOT NULL,
  `Inscricao_Municipal` VARCHAR(11) NOT NULL,
  `CLIENTE_idCLIENTE` INT(8) NOT NULL,
  PRIMARY KEY (`CLIENTE_idCLIENTE`),
  CONSTRAINT `fk_CLIENTE_PJ_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `fabdev_fixmycar`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Caracteristicas` (
  `Marca` VARCHAR(45) NOT NULL,
  `Producao` VARCHAR(45) NOT NULL,
  `Data_de_validade` DATE NOT NULL,
  `Frete_Gratis` VARCHAR(6) NOT NULL,
  `Peso_Liquido` DECIMAL(6,2) NOT NULL,
  `Peso_Bruto` DECIMAL(6,2) NOT NULL,
  `Altura_cm` INT(8) NULL,
  `Largura_cm` INT(8) NULL,
  `Profundiddade_cm` INT(8) NULL,
  `PRODUTO_ENT_idPRODUTO_ENT` INT(8) NOT NULL,
  PRIMARY KEY (`PRODUTO_ENT_idPRODUTO_ENT`),
  CONSTRAINT `fk_Caracteristicas_PRODUTO_ENT1`
    FOREIGN KEY (`PRODUTO_ENT_idPRODUTO_ENT`)
    REFERENCES `fabdev_fixmycar`.`PRODUTO_ENT` (`idPRODUTO_ENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Login` (
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `COLABORADORES_idCOLABORADORES` INT(8) NOT NULL,
  PRIMARY KEY (`COLABORADORES_idCOLABORADORES`),
  CONSTRAINT `fk_Login_COLABORADORES1`
    FOREIGN KEY (`COLABORADORES_idCOLABORADORES`)
    REFERENCES `fabdev_fixmycar`.`COLABORADORES` (`idCOLABORADORES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`PRODUTO_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`PRODUTO_VENDA` (
  `idPV` INT(8) NOT NULL,
  `ESTOQUE_idESTOQUE` INT(8) NOT NULL,
  `ESTOQUE_valorVENDA` DECIMAL(6,2) NOT NULL,
  `QUANTIDADE` DECIMAL(6,2) NOT NULL,
  `ALICOTA_ICMS` DECIMAL(6,2) NOT NULL,
  `VALOR_TOTAL` DECIMAL(6,2) GENERATED ALWAYS AS (QUANTIDADE*ESTOQUE_valorVENDA*ALICOTA_ICMS) VIRTUAL,
  `ORCAMENTO_idORCAMENTO` INT(8) NOT NULL,
  `ORDEM_SERVICO_OS` INT(8) NOT NULL,
  PRIMARY KEY (`idPV`),
  INDEX `fk_PRODUTO_VENDA_ORDEM_SERVICO1_idx` (`ORDEM_SERVICO_OS` ASC) VISIBLE,
  INDEX `fk_PRODUTO_VENDA_ORCAMENTO1_idx` (`ORCAMENTO_idORCAMENTO` ASC) VISIBLE,
  INDEX `fk_PRODUTO_VENDA_ESTOQUE1_idx` (`ESTOQUE_idESTOQUE` ASC) VISIBLE,
  INDEX `fk_PRODUTO_VENDA_ESTOQUE2_idx` (`ESTOQUE_valorVENDA` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_VENDA_ORDEM_SERVICO1`
    FOREIGN KEY (`ORDEM_SERVICO_OS`)
    REFERENCES `fabdev_fixmycar`.`ORDEM_SERVICO` (`OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_VENDA_ORCAMENTO1`
    FOREIGN KEY (`ORCAMENTO_idORCAMENTO`)
    REFERENCES `fabdev_fixmycar`.`ORCAMENTO` (`idORCAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_VENDA_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_idESTOQUE`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`idESTOQUE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_VENDA_ESTOQUE2`
    FOREIGN KEY (`ESTOQUE_valorVENDA`)
    REFERENCES `fabdev_fixmycar`.`ESTOQUE` (`valorVENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`dados_gerais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`dados_gerais` (
  `Numero_RPS` INT NULL,
  `Serie_RPS` INT NULL,
  `Numero_NFS-e` INT NULL,
  `Data_emissao` DATE NULL,
  `Natureza_de_operacao` VARCHAR(50) NULL,
  `Nota_de_Servico_idNFServico` INT(8) NOT NULL,
  INDEX `fk_dados_gerais_Nota_de_Servico1_idx` (`Nota_de_Servico_idNFServico` ASC) VISIBLE,
  PRIMARY KEY (`Nota_de_Servico_idNFServico`),
  CONSTRAINT `fk_dados_gerais_Nota_de_Servico1`
    FOREIGN KEY (`Nota_de_Servico_idNFServico`)
    REFERENCES `fabdev_fixmycar`.`Nota_de_Servico` (`idNFServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Total_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Total_Servico` (
  `Total_dos_Servicos` DECIMAL(6,2) NOT NULL,
  `Base_de_calculo` DECIMAL(6,2) NOT NULL,
  `Total_da_Nota` DECIMAL(6,2) NOT NULL,
  `Nota_de_Servico_idNFServico` INT(8) NOT NULL,
  INDEX `fk_Total_Servico_Nota_de_Servico1_idx` (`Nota_de_Servico_idNFServico` ASC) VISIBLE,
  PRIMARY KEY (`Nota_de_Servico_idNFServico`),
  CONSTRAINT `fk_Total_Servico_Nota_de_Servico1`
    FOREIGN KEY (`Nota_de_Servico_idNFServico`)
    REFERENCES `fabdev_fixmycar`.`Nota_de_Servico` (`idNFServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Impostos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Impostos` (
  `%IR` DECIMAL(6,2) NULL,
  `Valor do IR` DECIMAL(6,2) NULL,
  `%ISS` DECIMAL(6,2) NULL,
  `Valor_do_ISS` DECIMAL(6,2) NULL,
  `Reter_ISS` DECIMAL(6,2) NULL,
  `Descontar_ISS` DECIMAL(6,2) NULL,
  `Reter_INSS` DECIMAL(6,2) NULL,
  `Reter_CSLL_PIS_e_COFINS` DECIMAL(6,2) NULL,
  `% Aprox_Trib_ IBPT` DECIMAL(6,2) NULL,
  `Valor_Aprox_Trib` DECIMAL(6,2) NULL,
  `Nota_de_Servico_idNFServico` INT(8) NOT NULL,
  INDEX `fk_Impostos_Nota_de_Servico1_idx` (`Nota_de_Servico_idNFServico` ASC) VISIBLE,
  PRIMARY KEY (`Nota_de_Servico_idNFServico`),
  CONSTRAINT `fk_Impostos_Nota_de_Servico1`
    FOREIGN KEY (`Nota_de_Servico_idNFServico`)
    REFERENCES `fabdev_fixmycar`.`Nota_de_Servico` (`idNFServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Servicos_NFSe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Servicos_NFSe` (
  `Descricao` VARCHAR(255) NULL,
  `Valor` DECIMAL(6,2) NULL,
  `Conjunto_de_tributacoes` VARCHAR(15) NULL,
  `Codigo_do_servico` VARCHAR(15) NULL,
  `CNAE` VARCHAR(15) NULL,
  `Nota_de_Servico_idNFServico` INT(8) NOT NULL,
  INDEX `fk_Servicos_NFSe_Nota_de_Servico1_idx` (`Nota_de_Servico_idNFServico` ASC) VISIBLE,
  PRIMARY KEY (`Nota_de_Servico_idNFServico`),
  CONSTRAINT `fk_Servicos_NFSe_Nota_de_Servico1`
    FOREIGN KEY (`Nota_de_Servico_idNFServico`)
    REFERENCES `fabdev_fixmycar`.`Nota_de_Servico` (`idNFServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Valores_e_Impostos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Valores_e_Impostos` (
  `Base_ICMS` DECIMAL(6,2) NULL,
  `Valor_ICMS` DECIMAL(6,2) NULL,
  `Base ICMS Subst` DECIMAL(6,2) NULL,
  `Valor_ICMS_Subs` DECIMAL(6,2) NULL,
  `Valor_Total_dos_Produtos` DECIMAL(6,2) NULL,
  `Valor_do_Frete` DECIMAL(6,2) NULL,
  `Valor_do_Seguro` DECIMAL(6,2) NULL,
  `Desconto` DECIMAL(6,2) NULL,
  `Valor_dos_Acessórios` DECIMAL(6,2) NULL,
  `Valor_total_do_IPI` DECIMAL(6,2) NULL,
  `Valor_Tota_da_Nota_Fiscal` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_Valores_e_Impostos_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_Valores_e_Impostos_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ICMS_UF_DESTINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ICMS_UF_DESTINO` (
  `Valor_Base_ICMS` DECIMAL(6,2) NULL,
  `%_FCP` DECIMAL(6,2) NULL,
  `ICMS_UF_DESTINO` DECIMAL(6,2) NULL,
  `Valor_ICMS_FCP` DECIMAL(6,2) NULL,
  `%_Partilha_ICMS` DECIMAL(6,2) NULL,
  `%_Interestadual_UF` DECIMAL(6,2) NULL,
  `%_ICMS_Interno_UF_destino` DECIMAL(6,2) NULL,
  `Valor_ICMS_para_a_UF_destino` DECIMAL(6,2) NULL,
  `Valor_ICMS_para_a_UF_do_Remetente` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_ICMS_UF_DESTINO_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_ICMS_UF_DESTINO_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Itens` (
  `Peca/Produto` VARCHAR(50) NOT NULL,
  `Quantidade` DECIMAL(6,2) NULL,
  `Valor_Unitario` DECIMAL(6,2) NULL,
  `Valor_do_Desconto` DECIMAL(6,2) NULL,
  `Valor_de_Frete` DECIMAL(6,2) NULL,
  `Valor_de_Acessorio` DECIMAL(6,2) NULL,
  `Valor_de_ seguro` DECIMAL(6,2) NULL,
  `Valor_total_ de_item` DECIMAL(6,2) NULL,
  `Local_de_Estoque` VARCHAR(50) NOT NULL,
  `Natureza_Fiscal` VARCHAR(50) NULL,
  `Valor_total_do_ item_na_NF-e` DECIMAL(6,2) NULL,
  `Cliente_B2B` VARCHAR(50) NULL,
  `Numero_do_ pedido_de_compra` INT(8) NULL,
  `Item_do_pedido_de_compra` VARCHAR(50) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_Itens_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`Local_de_Estoque`, `NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_Itens_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Outros_Impostos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Outros_Impostos` (
  `Valor_PIS` DECIMAL(6,2) NULL,
  `Valor_COFINS` DECIMAL(6,2) NULL,
  `Valor_ICMS_para_a_UF_de_ destino` DECIMAL(6,2) NULL,
  `Valor_ICMS_para_a_UF_do_ remetente` DECIMAL(6,2) NULL,
  `Valor_IBPT_Federal` DECIMAL(6,2) NULL,
  `Valor_IBPT_Estadual` DECIMAL(6,2) NULL,
  `Valor_IBPT_Importacao` DECIMAL(6,2) NULL,
  `Valor_ FCP` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_Outros_Impostos_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_Outros_Impostos_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`COFINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`COFINS` (
  `%_COFINS` DECIMAL(6,2) NULL,
  `Valor_Base_COFINS` DECIMAL(6,2) NULL,
  `Valor_COFINS` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_COFINS_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_COFINS_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ICMS_ST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ICMS_ST` (
  `Valor_Base_ICMS_ST` DECIMAL(6,2) NULL,
  `%_ICMS_ST` DECIMAL(6,2) NULL,
  `Valor_ICMS_ST` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_ICMS_ST_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_ICMS_ST_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`PIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`PIS` (
  `%_PIS` DECIMAL(6,2) NULL,
  `Valor_Base_PIS` DECIMAL(6,2) NULL,
  `Valor_PIS` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_PIS_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_PIS_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`IPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`IPI` (
  `%_IPI` DECIMAL(6,2) NULL,
  `Valor_Base_IPI` DECIMAL(6,2) NULL,
  `Valor_IPI` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_IPI_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_IPI_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`IBPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`IBPT` (
  `Valor_Impostos_Federais` DECIMAL(6,2) NULL,
  `Valor_Impostos_Estaduais` DECIMAL(6,2) NULL,
  `Valor_Impostos_Importacao` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_IBPT_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_IBPT_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`ICMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`ICMS` (
  `%_ICMS` DECIMAL(6,2) NULL,
  `%_Base_Redução_de_ICMS` DECIMAL(6,2) NULL,
  `Valor_Base_ICMS` DECIMAL(6,2) NULL,
  `Valor_ICMS` DECIMAL(6,2) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_ICMS_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_ICMS_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`Transportador/Volume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`Transportador/Volume` (
  `Transportadora` VARCHAR(50) NULL,
  `Emitente` VARCHAR(50) NULL,
  `Destinatario` VARCHAR(50) NULL,
  `Terceiros` VARCHAR(50) NULL,
  `Sem_frete` VARCHAR(50) NULL,
  `Endereco_do_Transportador` VARCHAR(100) NULL,
  `Municipio` VARCHAR(100) NULL,
  `UF` VARCHAR(2) NULL,
  `Inscricao_Estadual` VARCHAR(100) NULL,
  `Quantidade` DECIMAL(6,2) NULL,
  `Especie` VARCHAR(100) NULL,
  `Marca` VARCHAR(100) NULL,
  `Numeracao` VARCHAR(45) NULL,
  `Peso_Bruto` DECIMAL(6,2) NULL,
  `Peso_Liquido` DECIMAL(6,2) NULL,
  `Placa_do_Veiculo` VARCHAR(7) NULL,
  `Registro_ANTT` VARCHAR(100) NULL,
  `Nota_Referenciada` VARCHAR(100) NULL,
  `NOTA_FISCAL_SAIDA_idNFISCAL` INT(8) NOT NULL,
  INDEX `fk_Transportador/Volume_NOTA_FISCAL_SAIDA1_idx` (`NOTA_FISCAL_SAIDA_idNFISCAL` ASC) VISIBLE,
  PRIMARY KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`),
  CONSTRAINT `fk_Transportador/Volume_NOTA_FISCAL_SAIDA1`
    FOREIGN KEY (`NOTA_FISCAL_SAIDA_idNFISCAL`)
    REFERENCES `fabdev_fixmycar`.`NOTA_FISCAL_SAIDA` (`idNFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`IMAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`IMAGENS` (
  `IdIMAGENS` INT(8) NOT NULL AUTO_INCREMENT,
  `IMAGEM` BLOB NOT NULL,
  `descricao_imagem` VARCHAR(255) NULL,
  `RELATORIO_FINAL_idRELATORIO_FINAL` INT(8) NOT NULL,
  INDEX `fk_IMAGENS_RELATORIO_FINAL1_idx` (`RELATORIO_FINAL_idRELATORIO_FINAL` ASC) VISIBLE,
  PRIMARY KEY (`IdIMAGENS`),
  CONSTRAINT `fk_IMAGENS_RELATORIO_FINAL1`
    FOREIGN KEY (`RELATORIO_FINAL_idRELATORIO_FINAL`)
    REFERENCES `fabdev_fixmycar`.`RELATORIO_FINAL` (`idRELATORIO_FINAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabdev_fixmycar`.`IMAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabdev_fixmycar`.`IMAGENS` (
  `IdIMAGENS` INT(8) NOT NULL AUTO_INCREMENT,
  `IMAGEM` BLOB NOT NULL,
  `descricao_imagem` VARCHAR(255) NULL,
  `RELATORIO_FINAL_idRELATORIO_FINAL` INT(8) NOT NULL,
  INDEX `fk_IMAGENS_RELATORIO_FINAL1_idx` (`RELATORIO_FINAL_idRELATORIO_FINAL` ASC) VISIBLE,
  PRIMARY KEY (`IdIMAGENS`),
  CONSTRAINT `fk_IMAGENS_RELATORIO_FINAL1`
    FOREIGN KEY (`RELATORIO_FINAL_idRELATORIO_FINAL`)
    REFERENCES `fabdev_fixmycar`.`RELATORIO_FINAL` (`idRELATORIO_FINAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
